# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-19 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_author_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ninja',
            name='dojo',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='author',
        ),
        migrations.DeleteModel(
            name='dojo',
        ),
        migrations.DeleteModel(
            name='ninja',
        ),
        migrations.AddField(
            model_name='book',
            name='liked_by',
            field=models.ManyToManyField(related_name='uploaded_books', to='first_app.user'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='first_app.user'),
            preserve_default=False,
        ),
    ]
