# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-19 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20180419_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_books', to='first_app.user'),
        ),
    ]
