# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-21 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20180419_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='book',
        ),
    ]
