# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20180423_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='first_name',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='password',
        ),
    ]
