# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_remove_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='first_app.user'),
            preserve_default=False,
        ),
    ]
