# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-25 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0019_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='speaker',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
