# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-25 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0020_quote_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
