# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-25 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0022_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='speaker',
            field=models.CharField(max_length=255, null='Anonymous'),
        ),
    ]
