# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-25 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0023_auto_20180425_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='speaker',
            field=models.CharField(default='Anonymous', max_length=255),
            preserve_default=False,
        ),
    ]
